'use client';

import React, { useEffect, useState } from 'react';
import { ShieldCheck, ShieldAlert, CheckCircle2, XCircle, Clock, AlertTriangle, ArrowRight } from 'lucide-react';
import { fetchApi } from '@/lib/api';

export default function ApprovalsPage() {
  const [approvals, setApprovals] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [processingId, setProcessingId] = useState<string | null>(null);

  useEffect(() => {
    loadApprovals();
  }, []);

  async function loadApprovals() {
    try {
      setLoading(true);
      const data = await fetchApi('/approvals');
      setApprovals(data);
    } catch (err) {
      console.error('Failed to load approvals:', err);
    } finally {
      setLoading(false);
    }
  }

  const handleReview = async (id: string, approved: boolean) => {
    try {
      setProcessingId(id);
      await fetchApi(`/approvals/${id}/review`, {
        method: 'POST',
        body: JSON.stringify({ approved })
      });
      await loadApprovals();
    } catch (err: any) {
      alert(`Error reviewing approval: ${err.message}`);
    } finally {
      setProcessingId(null);
    }
  };

  const getRiskBadge = (risk: string) => {
    switch (risk) {
      case 'CRITICAL':
        return <span className="px-2.5 py-1 rounded-full bg-red-500/20 text-red-400 font-bold border border-red-500/40 animate-pulse">CRITICAL RISK</span>;
      case 'HIGH':
        return <span className="px-2.5 py-1 rounded-full bg-amber-500/20 text-amber-400 font-bold border border-amber-500/40">HIGH RISK</span>;
      case 'MEDIUM':
        return <span className="px-2.5 py-1 rounded-full bg-blue-500/20 text-blue-400 font-bold border border-blue-500/40">MEDIUM RISK</span>;
      default:
        return <span className="px-2.5 py-1 rounded-full bg-slate-800 text-slate-400 font-bold border border-slate-700">LOW RISK</span>;
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-white tracking-wide">Human-in-the-Loop Approval Queue</h1>
        <p className="text-sm text-slate-400 mt-1">Review medium and high-risk operational actions generated by AI before execution</p>
      </div>

      {/* Approvals Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {loading ? (
          <div className="col-span-full p-12 text-center text-slate-500">Loading approval queue...</div>
        ) : approvals.length === 0 ? (
          <div className="col-span-full p-12 text-center text-slate-500">No pending or historical approvals found.</div>
        ) : (
          approvals.map((app) => (
            <div
              key={app.id}
              className={`p-6 rounded-2xl bg-[#111827] border flex flex-col justify-between transition ${
                app.status === 'PENDING' ? 'border-amber-500/40 shadow-lg shadow-amber-500/5' : 'border-slate-800 opacity-80'
              }`}
            >
              <div>
                <div className="flex items-start justify-between gap-3 mb-4">
                  <div>
                    <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider block mb-1">
                      Ref Action #{app.action_id.slice(0, 8)}
                    </span>
                    <h3 className="font-bold text-base text-white">{app.title}</h3>
                  </div>
                  <div>{getRiskBadge(app.risk_level)}</div>
                </div>

                <p className="text-xs text-slate-300 mb-4 bg-slate-900/80 p-3 rounded-xl border border-slate-800/80">
                  {app.reason}
                </p>

                {/* Payload details */}
                <div className="mb-4 text-xs font-mono bg-slate-950 p-3 rounded-xl border border-slate-800 text-slate-300">
                  <p className="text-[10px] text-slate-500 uppercase font-semibold mb-1">Action Payload</p>
                  <pre className="whitespace-pre-wrap">{JSON.stringify(app.payload, null, 2)}</pre>
                </div>
              </div>

              {/* Status and Action Buttons */}
              <div className="pt-4 border-t border-slate-800 flex items-center justify-between">
                <div className="text-xs text-slate-400">
                  <span>Requested by: <strong className="text-slate-200">{app.created_by}</strong></span>
                </div>

                {app.status === 'PENDING' ? (
                  <div className="flex items-center space-x-2">
                    <button
                      disabled={processingId === app.id}
                      onClick={() => handleReview(app.id, false)}
                      className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-red-500/20 hover:text-red-400 hover:border-red-500/40 text-slate-300 font-bold text-xs border border-slate-700 transition"
                    >
                      Reject
                    </button>
                    <button
                      disabled={processingId === app.id}
                      onClick={() => handleReview(app.id, true)}
                      className="px-4 py-2 rounded-lg bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-bold text-xs flex items-center space-x-1.5 transition"
                    >
                      <CheckCircle2 className="w-4 h-4" />
                      <span>Approve & Execute</span>
                    </button>
                  </div>
                ) : (
                  <span className={`px-3 py-1 rounded-lg text-xs font-bold ${
                    app.status === 'EXECUTED' ? 'bg-emerald-500/20 text-emerald-400' : 'bg-red-500/20 text-red-400'
                  }`}>
                    {app.status}
                  </span>
                )}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
